/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import {
  Activity,
  ArrowDownToLine,
  ArrowUpFromLine,
  CircleDollarSign,
  Coins,
  WalletCards,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'

import { Card, CardContent } from '@/components/ui/card'
import { IconBadge, type IconBadgeTone } from '@/components/ui/icon-badge'
import { Skeleton } from '@/components/ui/skeleton'
import { toIntlLocale } from '@/i18n/languages'
import { formatCompactNumber, formatQuota } from '@/lib/format'

import { formatBillingDuration } from '../lib'
import type { BillingFunds, BillingSummary } from '../types'

type BillingSummaryProps = {
  summary?: BillingSummary
  funds?: BillingFunds
  loading: boolean
}

export function BillingSummaryCards(props: BillingSummaryProps) {
  const { t, i18n } = useTranslation()
  const locale = toIntlLocale(i18n.resolvedLanguage)
  const cards: {
    label: string
    value: string
    description: string
    icon: typeof Coins
    tone: IconBadgeTone
  }[] = [
    {
      label: t('Period Cost'),
      value: formatQuota(props.summary?.net_quota ?? 0),
      description: t('Final settled usage cost'),
      icon: CircleDollarSign,
      tone: 'warning',
    },
    {
      label: t('Total Tokens'),
      value: formatCompactNumber(props.summary?.total_tokens ?? 0, locale),
      description: t('Input and output tokens'),
      icon: Coins,
      tone: 'primary',
    },
    {
      label: t('Input Tokens'),
      value: formatCompactNumber(props.summary?.prompt_tokens ?? 0, locale),
      description: t('Tokens sent to models'),
      icon: ArrowUpFromLine,
      tone: 'info',
    },
    {
      label: t('Output Tokens'),
      value: formatCompactNumber(props.summary?.completion_tokens ?? 0, locale),
      description: t('Tokens generated by models'),
      icon: ArrowDownToLine,
      tone: 'chart-4',
    },
    {
      label: t('API Requests'),
      value: formatCompactNumber(props.summary?.requests ?? 0, locale),
      description: t('Settled model calls'),
      icon: Activity,
      tone: 'success',
    },
    {
      label: t('Current Balance'),
      value: formatQuota(props.funds?.current_balance ?? 0),
      description: t('Lifetime consumed: {{amount}}', {
        amount: formatQuota(props.funds?.lifetime_consumed ?? 0),
      }),
      icon: WalletCards,
      tone: 'chart-3',
    },
  ]

  return (
    <>
      <div className='grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6'>
        {cards.map((card) => (
          <Card key={card.label} size='sm'>
            <CardContent>
              <div className='flex items-center gap-2'>
                <IconBadge tone={card.tone} size='stat'>
                  <card.icon />
                </IconBadge>
                <span className='text-muted-foreground truncate text-[11px] font-medium tracking-wide uppercase'>
                  {card.label}
                </span>
              </div>
              {props.loading ? (
                <>
                  <Skeleton className='mt-3 h-6 w-24' />
                  <Skeleton className='mt-2 h-3 w-full' />
                </>
              ) : (
                <>
                  <div className='mt-2 font-mono text-lg font-bold tracking-tight break-all tabular-nums sm:text-xl'>
                    {card.value}
                  </div>
                  <p className='text-muted-foreground mt-1 line-clamp-1 text-xs'>
                    {card.description}
                  </p>
                </>
              )}
            </CardContent>
          </Card>
        ))}
      </div>

      <Card size='sm'>
        <CardContent className='grid grid-cols-2 divide-x divide-y sm:grid-cols-4 sm:divide-y-0'>
          {[
            {
              label: t('Average RPM'),
              value: (props.summary?.average_rpm ?? 0).toLocaleString(locale, {
                maximumFractionDigits: 2,
              }),
            },
            {
              label: t('Average TPM'),
              value: (props.summary?.average_tpm ?? 0).toLocaleString(locale, {
                maximumFractionDigits: 2,
              }),
            },
            {
              label: t('Average Response Time'),
              value: formatBillingDuration(
                props.summary?.average_use_time_seconds ?? 0,
                locale
              ),
            },
            {
              label: t('Streaming Requests'),
              value: new Intl.NumberFormat(locale, {
                style: 'percent',
                maximumFractionDigits: 1,
              }).format(props.summary?.stream_ratio ?? 0),
            },
          ].map((metric) => (
            <div
              key={metric.label}
              className='min-w-0 px-3 py-2 first:pl-0 last:pr-0 sm:py-0'
            >
              <div className='text-muted-foreground truncate text-xs'>
                {metric.label}
              </div>
              {props.loading ? (
                <Skeleton className='mt-1.5 h-5 w-16' />
              ) : (
                <div className='mt-1 font-mono text-sm font-semibold tabular-nums'>
                  {metric.value}
                </div>
              )}
            </div>
          ))}
        </CardContent>
      </Card>
    </>
  )
}
